name: Build and Push to ECR

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  build_and_push:
    if: github.event.pull_request.merged == true || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
